In [1]:
import pandas as pd
import Recuperacion as re

In [2]:
df = re.Funcion_1('Estocolmo.csv')
df = df.drop(['Unnamed: 0'], axis=1)
df

,last_scraped,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2024-12-30,2011-07-06,within an hour,100%,100%,t,2,2,t,t,...,4.95,4.97,4.84,4.76,NaN,f,2,0,2,0
1,2024-12-30,2011-02-27,within a day,100%,15%,f,2,4,t,t,...,4.87,4.88,4.81,4.70,NaN,f,2,1,1,0
2,2024-12-30,2011-10-05,within a few hours,100%,0%,f,1,1,t,t,...,4.85,4.95,4.85,4.64,NaN,f,1,1,0,0
3,2024-12-30,2011-07-06,within an hour,100%,100%,t,2,2,t,t,...,4.96,4.98,4.89,4.84,NaN,f,2,0,2,0
4,2024-12-30,2011-11-22,within a few hours,100%,100%,f,3,3,t,t,...,5.00,4.75,5.00,5.00,NaN,f,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5218,2024-12-30,2014-11-16,NaN,NaN,NaN,f,2,2,t,f,...,NaN,NaN,NaN,NaN,NaN,f,1,1,0,0
5219,2024-12-30,2021-10-04,NaN,NaN,NaN,f,1,1,t,f,...,NaN,NaN,NaN,NaN,NaN,f,1,1,0,0
5220,2024-12-30,2021-02-23,NaN,NaN,NaN,f,2,3,t,f,...,NaN,NaN,NaN,NaN,NaN,f,1,0,1,0
5221,2024-12-30,2013-05-09,NaN,NaN,NaN,f,1,1,t,t,...,NaN,NaN,NaN,NaN,NaN,t,1,1,0,0
5222,2024-12-30,2024-12-28,NaN,NaN,NaN,f,1,1,f,t,...,NaN,NaN,NaN,NaN,NaN,t,1,1,0,0

In [3]:
df = re.Funcion_2(df)
df

c:\Users\italy\Downloads\Clase alfredo\Evaluación\Recuperacion.py:44: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna("Valor Nulo", inplace=True)
c:\Users\italy\Downloads\Clase alfredo\Evaluación\Recuperacion.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(1000001, inplace=True)
c:\Users\italy\Downloads\Clase alfredo\Evaluación\Recuperacion.py:38: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(1111111, inplace=True)

,last_scraped,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2024-12-30,2011-07-06,within an hour,100%,100%,t,2,2,t,t,...,4.95,4.97,4.84,4.76,1000001.0,f,2,0,2,0
1,2024-12-30,2011-02-27,within a day,100%,15%,f,2,4,t,t,...,4.87,4.88,4.81,4.70,1000001.0,f,2,1,1,0
2,2024-12-30,2011-10-05,within a few hours,100%,0%,f,1,1,t,t,...,4.85,4.95,4.85,4.64,1000001.0,f,1,1,0,0
3,2024-12-30,2011-07-06,within an hour,100%,100%,t,2,2,t,t,...,4.96,4.98,4.89,4.84,1000001.0,f,2,0,2,0
4,2024-12-30,2011-11-22,within a few hours,100%,100%,f,3,3,t,t,...,5.00,4.75,5.00,5.00,1000001.0,f,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5218,2024-12-30,2014-11-16,Valor Nulo,Valor Nulo,Valor Nulo,f,2,2,t,f,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,f,1,1,0,0
5219,2024-12-30,2021-10-04,Valor Nulo,Valor Nulo,Valor Nulo,f,1,1,t,f,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,f,1,1,0,0
5220,2024-12-30,2021-02-23,Valor Nulo,Valor Nulo,Valor Nulo,f,2,3,t,f,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,f,1,0,1,0
5221,2024-12-30,2013-05-09,Valor Nulo,Valor Nulo,Valor Nulo,f,1,1,t,t,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,t,1,1,0,0
5222,2024-12-30,2024-12-28,Valor Nulo,Valor Nulo,Valor Nulo,f,1,1,f,t,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,t,1,1,0,0

In [4]:
#Hacemos el conteo de datos nulos
df = re.Funcion_3(df)
df

Valores nulos por columna:
last_scraped                                    0
host_since                                      0
host_response_time                              0
host_response_rate                              0
host_acceptance_rate                            0
host_is_superhost                               0
host_listings_count                             0
host_total_listings_count                       0
host_has_profile_pic                            0
host_identity_verified                          0
latitude                                        0
longitude                                       0
property_type                                   0
room_type                                       0
accommodates                                    0
bathrooms                                       0
bathrooms_text                                  0
bedrooms                                        0
beds                                            0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
has_availability                                0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
calendar_last_scraped                           0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
first_review                                    0
last_review                                     0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
license                                         0
instant_bookable                                0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
dtype: int64
Valores nulos en el DataFrame: 0

,last_scraped,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2024-12-30,2011-07-06,within an hour,100%,100%,t,2,2,t,t,...,4.95,4.97,4.84,4.76,1000001.0,f,2,0,2,0
1,2024-12-30,2011-02-27,within a day,100%,15%,f,2,4,t,t,...,4.87,4.88,4.81,4.70,1000001.0,f,2,1,1,0
2,2024-12-30,2011-10-05,within a few hours,100%,0%,f,1,1,t,t,...,4.85,4.95,4.85,4.64,1000001.0,f,1,1,0,0
3,2024-12-30,2011-07-06,within an hour,100%,100%,t,2,2,t,t,...,4.96,4.98,4.89,4.84,1000001.0,f,2,0,2,0
4,2024-12-30,2011-11-22,within a few hours,100%,100%,f,3,3,t,t,...,5.00,4.75,5.00,5.00,1000001.0,f,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5218,2024-12-30,2014-11-16,Valor Nulo,Valor Nulo,Valor Nulo,f,2,2,t,f,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,f,1,1,0,0
5219,2024-12-30,2021-10-04,Valor Nulo,Valor Nulo,Valor Nulo,f,1,1,t,f,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,f,1,1,0,0
5220,2024-12-30,2021-02-23,Valor Nulo,Valor Nulo,Valor Nulo,f,2,3,t,f,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,f,1,0,1,0
5221,2024-12-30,2013-05-09,Valor Nulo,Valor Nulo,Valor Nulo,f,1,1,t,t,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,t,1,1,0,0
5222,2024-12-30,2024-12-28,Valor Nulo,Valor Nulo,Valor Nulo,f,1,1,f,t,...,1000001.00,1111111.00,1000001.00,1111111.00,1000001.0,t,1,1,0,0

In [5]:
df = re.Funcion_4(df)
df

,last_scraped,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,property_type,room_type,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2024-12-30,2011-07-06,within an hour,100%,100%,t,t,t,Private room in rental unit,Private room,...,4.79,4.95,4.97,4.84,4.76,1000001.0,2.0,Valor Atípico,Valor Atípico,0.0
1,2024-12-30,2011-02-27,within a day,100%,15%,f,t,t,Private room in rental unit,Private room,...,4.63,4.87,4.88,4.81,4.7,1000001.0,2.0,1.0,Valor Atípico,0.0
2,2024-12-30,2011-10-05,within a few hours,100%,0%,f,t,t,Entire rental unit,Entire home/apt,...,4.71,4.85,4.95,4.85,4.64,1000001.0,1.0,1.0,0.0,0.0
3,2024-12-30,2011-07-06,within an hour,100%,100%,t,t,t,Private room in rental unit,Private room,...,4.84,4.96,4.98,4.89,4.84,1000001.0,2.0,Valor Atípico,Valor Atípico,0.0
4,2024-12-30,2011-11-22,within a few hours,100%,100%,f,t,t,Entire rental unit,Entire home/apt,...,5.0,5.0,Valor Atípico,5.0,5.0,1000001.0,2.0,Valor Atípico,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5218,2024-12-30,2014-11-16,Valor Nulo,Valor Nulo,Valor Nulo,f,t,f,Entire rental unit,Entire home/apt,...,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,1000001.0,1.0,1.0,0.0,0.0
5219,2024-12-30,2021-10-04,Valor Nulo,Valor Nulo,Valor Nulo,f,t,f,Entire rental unit,Entire home/apt,...,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,1000001.0,1.0,1.0,0.0,0.0
5220,2024-12-30,2021-02-23,Valor Nulo,Valor Nulo,Valor Nulo,f,t,f,Private room in rental unit,Private room,...,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,1000001.0,1.0,Valor Atípico,Valor Atípico,0.0
5221,2024-12-30,2013-05-09,Valor Nulo,Valor Nulo,Valor Nulo,f,t,t,Entire home,Entire home/apt,...,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,1000001.0,1.0,1.0,0.0,0.0
5222,2024-12-30,2024-12-28,Valor Nulo,Valor Nulo,Valor Nulo,f,f,t,Entire rental unit,Entire home/apt,...,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,Valor Atípico,1000001.0,1.0,1.0,0.0,0.0